"""Initial migration for all tables

Revision ID: 1778d9f5ab8c
Revises: 703b0f20b407
Create Date: 2025-08-21 18:04:02.927669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1778d9f5ab8c'
down_revision = '703b0f20b407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index('idx_books_author', ['author'], unique=False)
        batch_op.create_index('idx_books_category_id', ['category_id'], unique=False)
        batch_op.create_index('idx_books_title', ['title'], unique=False)

    with op.batch_alter_table('borrowings', schema=None) as batch_op:
        batch_op.create_index('idx_borrowings_book_id', ['book_id'], unique=False)
        batch_op.create_index('idx_borrowings_borrowed_at', ['borrowed_at'], unique=False)
        batch_op.create_index('idx_borrowings_borrower_room_number', ['borrower_room_number'], unique=False)
        batch_op.create_index('idx_borrowings_is_returned', ['is_returned'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowings', schema=None) as batch_op:
        batch_op.drop_index('idx_borrowings_is_returned')
        batch_op.drop_index('idx_borrowings_borrower_room_number')
        batch_op.drop_index('idx_borrowings_borrowed_at')
        batch_op.drop_index('idx_borrowings_book_id')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index('idx_books_title')
        batch_op.drop_index('idx_books_category_id')
        batch_op.drop_index('idx_books_author')

    # ### end Alembic commands ###
