"""Add optional email and phone to borrowings

Revision ID: 2df3fe353e11
Revises: 1778d9f5ab8c
Create Date: 2025-08-23 12:29:27.746489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df3fe353e11'
down_revision = '1778d9f5ab8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('borrower_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('borrowings', schema=None) as batch_op:
        batch_op.drop_column('borrower_phone')
        batch_op.drop_column('borrower_email')

    # ### end Alembic commands ###
